# Generated by Django 3.2.8 on 2021-10-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text="Nom de l'article", max_length=100)),
                ('price', models.IntegerField(help_text='Prix en Ariary')),
                ('remaining', models.IntegerField(help_text='Article Restant')),
                ('deleteItem', models.BooleanField(default=False)),
            ],
        ),
    ]
